name = "Little Improved Vanilla"
author = "anhgelus"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f27c848b542fac8ad2b479c70efe3ecdba6e675764822cc814680504b5e09682"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
