name = "Little Improved Vanilla"
author = "anhgelus"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2f68e7c62ce00e09db8b5491e02466d98eba252bbd4a26b414f6a437ab5b403"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
